Required Modules:
  Core:
    DBI
    DBD::SQLite
    POE
    POE::Component::IRC
    Module::Load
    Module::Refresh
    Config::Simple
    Getopt::Std

  google.pm:
    WWW::Mechanize
  
  http.pm:
    WWW::Mechanize
    
  maths.pm:
    IO::CaptureOutput
    
  misc.pm:
    WWW::Mechanize
    Math::Round

  mylife.pm:
    WWW::Mechanize

  netmon.pm:
    Math::Round

  tinyurl.pm:
    WWW::Shorten::TinyURL

  tv.pm:
    WWW::Mechanize
